# -*- coding: utf-8 -*-
"""Etapa 4 - NER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJphkbRM1KIWWa-Exs_N8-Oq-8-zIgOI
"""

# Legacy Colab cell (desativada para execução local):
# !pip install transformers torch pandas tqdm

import json
import pandas as pd
from transformers import pipeline
from tqdm import tqdm
import warnings
import numpy as np
warnings.filterwarnings('ignore')

# Caminhos dos arquivos
ARQUIVO_ENTRADA = "resultado_anotacao_02.json"
ARQUIVO_SAIDA_JSON = "sentencas_com_entidades.json"
ARQUIVO_SAIDA_CSV = "sentencas_com_entidades.csv"

# Nome do modelo no HuggingFace
MODELO_NER = "dominguesm/legal-bert-ner-base-cased-ptbr"

def converter_para_tipo_nativo(obj):
    """
    Converte tipos numpy/torch para tipos nativos do Python.

    Args:
        obj: Objeto a ser convertido

    Returns:
        Objeto convertido para tipo nativo do Python
    """
    if isinstance(obj, (np.integer, np.int64, np.int32)):
        return int(obj)
    elif isinstance(obj, (np.floating, np.float64, np.float32)):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    elif isinstance(obj, dict):
        return {key: converter_para_tipo_nativo(value) for key, value in obj.items()}
    elif isinstance(obj, list):
        return [converter_para_tipo_nativo(item) for item in obj]
    else:
        return obj

def carregar_json(caminho_arquivo):
    """
    Carrega o arquivo JSON com as sentenças.
    Suporta tanto JSON array quanto JSONL (uma linha por objeto).

    Args:
        caminho_arquivo (str): Caminho do arquivo JSON

    Returns:
        list: Lista de dicionários com 'sentenca' e 'label'
    """
    try:
        # Tenta carregar como JSON array
        with open(caminho_arquivo, 'r', encoding='utf-8') as f:
            dados = json.load(f)
        print(f"✓ Arquivo carregado como JSON array: {len(dados)} registros")
        #print(dados)
        return dados["dados"]
    except json.JSONDecodeError:
        # Se falhar, tenta carregar como JSONL (uma linha por objeto)
        dados = []
        with open(caminho_arquivo, 'r', encoding='utf-8') as f:
            for linha in f:
                if linha.strip():
                    dados.append(json.loads(linha))
        print(f"✓ Arquivo carregado como JSONL: {len(dados)} registros")
        return dados["dados"]

def inicializar_modelo_ner():
    """
    Inicializa o pipeline de NER com o modelo jurídico brasileiro.

    Returns:
        pipeline: Pipeline do HuggingFace configurado para NER
    """
    print(f"\n⏳ Carregando modelo: {MODELO_NER}")
    print("   (Isso pode demorar alguns minutos na primeira execução...)")

    ner_pipeline = pipeline(
        "ner",
        model=MODELO_NER,
        aggregation_strategy="simple",
        device=-1  # Use device=0 para GPU, -1 para CPU
    )

    print("✓ Modelo carregado com sucesso!\n")
    return ner_pipeline

def processar_entidades(resultado_ner):
    """
    Processa o resultado do pipeline NER para formato padronizado.
    Converte todos os valores para tipos nativos do Python.

    Args:
        resultado_ner (list): Lista de entidades retornadas pelo pipeline

    Returns:
        list: Lista de dicionários com informações das entidades
    """
    entidades = []

    for entidade in resultado_ner:
        entidades.append({
            "text": str(entidade["word"]),
            "label": str(entidade["entity_group"]),
            "start": int(entidade["start"]),
            "end": int(entidade["end"]),
            "score": float(round(float(entidade["score"]), 4))
        })

    return entidades

def aplicar_ner_em_sentencas(dados, ner_pipeline):
    """
    Aplica o modelo NER em todas as sentenças do dataset.

    Args:
        dados (list): Lista de dicionários com sentenças
        ner_pipeline: Pipeline de NER inicializado

    Returns:
        list: Dados enriquecidos com entidades identificadas
    """
    resultados = []

    print("🔍 Processando sentenças...\n")

    for i, item in enumerate(tqdm(dados, desc="Aplicando NER")):
        sentenca = item.get("sentenca", "")
        label_secao = item.get("label", "")

        # Aplica NER
        try:
            entidades_brutas = ner_pipeline(sentenca)
            entidades = processar_entidades(entidades_brutas)
        except Exception as e:
            print(f"\n⚠ Erro ao processar sentença {i}: {e}")
            entidades = []

        # Monta resultado
        resultado = {
            "id": i,
            "sentenca": sentenca,
            "label": label_secao,
            "entidades": entidades,
            "num_entidades": len(entidades)
        }

        resultados.append(resultado)

    print(f"\n✓ Processamento concluído: {len(resultados)} sentenças analisadas\n")
    return resultados

def salvar_json(dados, caminho_arquivo):
    """
    Salva os resultados em formato JSON.
    Converte todos os tipos para tipos nativos do Python antes de salvar.

    Args:
        dados (list): Dados a serem salvos
        caminho_arquivo (str): Caminho do arquivo de saída
    """
    # Converte todos os dados para tipos nativos
    dados_convertidos = converter_para_tipo_nativo(dados)

    with open(caminho_arquivo, 'w', encoding='utf-8') as f:
        json.dump(dados_convertidos, f, ensure_ascii=False, indent=2)
    print(f"✓ Arquivo JSON salvo: {caminho_arquivo}")

def salvar_csv(dados, caminho_arquivo):
    """
    Salva os resultados em formato CSV.
    Como cada sentença pode ter múltiplas entidades, cada linha representa uma entidade.

    Args:
        dados (list): Dados a serem salvos
        caminho_arquivo (str): Caminho do arquivo de saída
    """
    linhas = []

    for item in dados:
        if item["entidades"]:
            for entidade in item["entidades"]:
                linhas.append({
                    "id": item["id"],
                    "sentenca": item["sentenca"],
                    "secao": item["label"],
                    "entidade_texto": entidade["text"],
                    "entidade_label": entidade["label"],
                    "entidade_start": entidade["start"],
                    "entidade_end": entidade["end"],
                    "entidade_score": entidade["score"]
                })
        else:
            # Linha sem entidades
            linhas.append({
                "id": item["id"],
                "sentenca": item["sentenca"],
                "secao": item["label"],
                "entidade_texto": None,
                "entidade_label": None,
                "entidade_start": None,
                "entidade_end": None,
                "entidade_score": None
            })

    df = pd.DataFrame(linhas)
    df.to_csv(caminho_arquivo, index=False, encoding='utf-8-sig')
    print(f"✓ Arquivo CSV salvo: {caminho_arquivo}")

def exibir_exemplo(dados, num_exemplos=3):
    """
    Exibe exemplos do resultado do processamento.

    Args:
        dados (list): Dados processados
        num_exemplos (int): Número de exemplos a exibir
    """
    print("\n" + "="*80)
    print("📊 EXEMPLOS DE RESULTADOS")
    print("="*80 + "\n")

    for i, item in enumerate(dados[:num_exemplos]):
        print(f"--- EXEMPLO {i+1} ---")
        print(f"Seção: {item['label']}")
        print(f"Sentença: {item['sentenca'][:200]}...")
        print(f"Total de entidades encontradas: {item['num_entidades']}\n")

        if item['entidades']:
            print("Entidades identificadas:")
            for j, ent in enumerate(item['entidades'], 1):
                print(f"  {j}. [{ent['label']}] \"{ent['text']}\" "
                      f"(posição {ent['start']}-{ent['end']}, "
                      f"confiança: {ent['score']:.2%})")
        else:
            print("  Nenhuma entidade identificada.")

        print("\n" + "-"*80 + "\n")

def gerar_estatisticas(dados):
    """
    Gera estatísticas sobre as entidades identificadas.

    Args:
        dados (list): Dados processados
    """
    print("\n" + "="*80)
    print("📈 ESTATÍSTICAS GERAIS")
    print("="*80 + "\n")

    total_sentencas = len(dados)
    total_entidades = sum(item['num_entidades'] for item in dados)
    sentencas_com_entidades = sum(1 for item in dados if item['num_entidades'] > 0)

    print(f"Total de sentenças processadas: {total_sentencas}")
    print(f"Sentenças com entidades: {sentencas_com_entidades} "
          f"({sentencas_com_entidades/total_sentencas*100:.1f}%)")
    print(f"Total de entidades identificadas: {total_entidades}")
    print(f"Média de entidades por sentença: {total_entidades/total_sentencas:.2f}\n")

    # Contagem por tipo de entidade
    contagem_labels = {}
    for item in dados:
        for ent in item['entidades']:
            label = ent['label']
            contagem_labels[label] = contagem_labels.get(label, 0) + 1

    if contagem_labels:
        print("Distribuição por tipo de entidade:")
        for label, count in sorted(contagem_labels.items(), key=lambda x: x[1], reverse=True):
            print(f"  {label}: {count} ({count/total_entidades*100:.1f}%)")

    # Contagem por seção
    print("\n")
    contagem_secoes = {}
    for item in dados:
        secao = item['label']
        if secao not in contagem_secoes:
            contagem_secoes[secao] = {'sentencas': 0, 'entidades': 0}
        contagem_secoes[secao]['sentencas'] += 1
        contagem_secoes[secao]['entidades'] += item['num_entidades']

    print("Distribuição por seção:")
    for secao, stats in sorted(contagem_secoes.items()):
        media = stats['entidades'] / stats['sentencas'] if stats['sentencas'] > 0 else 0
        print(f"  {secao}: {stats['sentencas']} sentenças, "
              f"{stats['entidades']} entidades (média: {media:.2f})")

    print("\n" + "="*80 + "\n")

def main():
    """
    Função principal que executa todo o pipeline de processamento.
    """
    print("\n" + "="*80)
    print("🏛️  SISTEMA DE NER JURÍDICO - SENTENÇAS PENAIS")
    print("="*80 + "\n")

    # 1. Carregar dados
    print("📂 PASSO 1: Carregando dados...")
    try:
        dados = carregar_json(ARQUIVO_ENTRADA)
    except FileNotFoundError:
        print(f"\n❌ ERRO: Arquivo '{ARQUIVO_ENTRADA}' não encontrado!")
        print("\nCriando arquivo de exemplo para demonstração...")
        criar_arquivo_exemplo()
        dados = carregar_json(ARQUIVO_ENTRADA)

    # 2. Inicializar modelo
    print("\n🤖 PASSO 2: Inicializando modelo de NER...")
    ner_pipeline = inicializar_modelo_ner()

    # 3. Processar sentenças
    print("⚙️  PASSO 3: Aplicando NER nas sentenças...")
    resultados = aplicar_ner_em_sentencas(dados, ner_pipeline)

    # 4. Exibir exemplos
    exibir_exemplo(resultados, num_exemplos=3)

    # 5. Gerar estatísticas
    gerar_estatisticas(resultados)

    # 6. Salvar resultados
    print("💾 PASSO 4: Salvando resultados...")
    salvar_json(resultados, ARQUIVO_SAIDA_JSON)
    salvar_csv(resultados, ARQUIVO_SAIDA_CSV)

    print("\n✅ PROCESSAMENTO CONCLUÍDO COM SUCESSO!\n")

def criar_arquivo_exemplo():
    """
    Cria um arquivo JSON de exemplo para demonstração.
    """
    exemplos = [
        {
            "sentenca": "O Juiz de Direito da 1ª Vara Criminal de São Paulo, Dr. João Silva, "
                       "nos autos do processo nº 0001234-56.2023.8.26.0100, em que é réu "
                       "José da Silva, brasileiro, solteiro, comerciante, portador do RG "
                       "nº 12.345.678-9, residente à Rua das Flores, nº 123, Centro, "
                       "proferiu a seguinte sentença.",
            "label": "RELATORIO"
        },
        {
            "sentenca": "O réu José da Silva foi denunciado como incurso nas sanções do "
                       "artigo 157, §2º, incisos I e II do Código Penal Brasileiro, "
                       "porque no dia 15 de janeiro de 2023, por volta das 22h, "
                       "na Avenida Paulista, nº 1000, subtraiu mediante grave ameaça "
                       "exercida com emprego de arma de fogo, em concurso com outros "
                       "indivíduos não identificados, a quantia de R$ 5.000,00 "
                       "pertencente à vítima Maria Santos.",
            "label": "FUNDAMENTACAO"
        },
        {
            "sentenca": "Ante o exposto, julgo procedente a ação penal e condeno o réu "
                       "José da Silva às penas do artigo 157, §2º, incisos I e II, "
                       "do Código Penal, fixando a pena em 6 anos de reclusão, "
                       "em regime inicial fechado, e ao pagamento de 15 dias-multa. "
                       "Custas pelo réu. Após o trânsito em julgado, lance-se o nome "
                       "do réu no rol dos culpados. São Paulo, 20 de março de 2023. "
                       "Dr. João Silva - Juiz de Direito.",
            "label": "DISPOSITIVO"
        },
        {
            "sentenca": "A testemunha Pedro Oliveira, policial militar, declarou que "
                       "no dia dos fatos estava em patrulhamento pela região quando "
                       "foi acionado via COPOM sobre um roubo em andamento. "
                       "Ao chegar ao local, na esquina da Rua Augusta com a Alameda Santos, "
                       "avistou o acusado fugindo em um veículo Fiat Uno de cor preta. "
                       "Após perseguição, o réu foi abordado e detido na Rua Consolação.",
            "label": "FUNDAMENTACAO"
        },
        {
            "sentenca": "Consta dos autos que a vítima Maria Santos, brasileira, "
                       "empresária, residente em Campinas/SP, compareceu à delegacia "
                       "para registrar boletim de ocorrência, relatando que foi "
                       "abordada por dois indivíduos em motocicleta, sendo que um deles "
                       "portava arma de fogo e exigiu a entrega de seus pertences, "
                       "incluindo bolsa contendo dinheiro e documentos.",
            "label": "RELATORIO"
        }
    ]

    with open(ARQUIVO_ENTRADA, 'w', encoding='utf-8') as f:
        json.dump(exemplos, f, ensure_ascii=False, indent=2)

    print(f"✓ Arquivo de exemplo criado: {ARQUIVO_ENTRADA}")

if __name__ == "__main__":
    main()