# -*- coding: utf-8 -*-
"""Etapa 3.2 - BERT como extrator + classificação.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w27nZVewSjeQOdmCp541eCSZXE1wMWsn

#### ============================================================================
#### 1. INSTALAÇÃO DE DEPENDÊNCIAS
#### ============================================================================
"""

print("📦 Instalando dependências...\n")

# Legacy Colab cell (desativada para execução local):
# !pip install -q sentence-transformers scikit-learn xgboost pandas numpy matplotlib seaborn tqdm

print("✅ Instalação concluída!\n")

"""#### ============================================================================
#### 2. IMPORTS
#### ============================================================================
"""

import os
import warnings
import numpy as np
import pandas as pd
from typing import List, Dict, Tuple, Any
from tqdm.auto import tqdm

# Sentence Transformers para embeddings
from sentence_transformers import SentenceTransformer

# Scikit-learn
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    classification_report, confusion_matrix
)

# XGBoost
import xgboost as xgb

# Visualização
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings('ignore')

print("✅ Imports realizados com sucesso!\n")

"""#### ============================================================================
#### 3. CONFIGURAÇÕES GLOBAIS
#### ============================================================================

"""

# Configurações gerais
SEED = 42
K_FOLDS = 3
BATCH_SIZE = 16

# Modelo BERT para embeddings
MODEL_NAME = "dominguesm/legal-bert-base-cased-ptbr"

# Fixar seeds para reprodutibilidade
np.random.seed(SEED)

# Configurações de visualização
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 8)
plt.rcParams['font.size'] = 10

print("🔧 Configurações:")
print(f"   • Modelo: {MODEL_NAME}")
print(f"   • K-Folds: {K_FOLDS}")
print(f"   • Seed: {SEED}")
print(f"   • Batch Size: {BATCH_SIZE}\n")

"""#### ============================================================================
#### 4. CARREGAMENTO DO DATASET
#### ============================================================================
"""

def carregar_dataset(csv_path: str) -> pd.DataFrame:
    """
    Carrega CSV com detecção automática de encoding e delimitador.

    Args:
        csv_path: Caminho para o arquivo CSV

    Returns:
        DataFrame com colunas 'text' e 'label'
    """
    print("📂 Carregando dataset...")

    delimiters = [';', ',', '\t', '|']
    encodings = ['utf-8', 'latin-1', 'iso-8859-1', 'cp1252']

    df = None

    for delimiter in delimiters:
        for encoding in encodings:
            try:
                df = pd.read_csv(
                    csv_path,
                    encoding=encoding,
                    delimiter=delimiter,
                    on_bad_lines='skip',
                    engine='python',
                    dtype=str,
                )

                if len(df.columns) > 1 and len(df) > 0:
                    print(f"   ✅ Encoding: {encoding}, Delimiter: '{delimiter}'")
                    break
            except Exception:
                continue

        if df is not None and len(df.columns) > 1:
            break

    if df is None or len(df.columns) <= 1:
        raise ValueError("❌ Não foi possível carregar o CSV corretamente")

    # Normalizar nomes das colunas
    df.columns = df.columns.str.strip().str.lower()

    # Identificar colunas de texto e label
    text_col = None
    label_col = None

    for col in df.columns:
        if 'texto_normalizado' in col and 'text' in col:
            text_col = col
        if 'decisao' in col or 'decisão' in col:
            label_col = col

    if text_col is None or label_col is None:
        print(f"   ⚠️ Colunas disponíveis: {df.columns.tolist()}")
        raise ValueError("❌ Colunas 'text' ou 'label' não encontradas")

    # Renomear e selecionar colunas
    df = df[[text_col, label_col]].copy()
    df.columns = ['text', 'label']

    # Limpeza básica
    df['text'] = df['text'].astype(str).str.strip()
    df['label'] = df['label'].astype(str).str.strip().str.lower()

    # Remover linhas vazias ou inválidas
    df = df.dropna()
    df = df[df['text'].str.len() > 10]
    df = df[df['label'].str.len() > 0]

    print(f"   ✅ {len(df)} documentos carregados\n")
    print("📊 Distribuição das classes:")
    print(df['label'].value_counts())
    print()

    return df

"""#### ============================================================================
#### 5. PRÉ-PROCESSAMENTO
#### ============================================================================
"""

def preprocessar_dados(df: pd.DataFrame) -> Tuple[pd.DataFrame, LabelEncoder]:
    """
    Prepara dados para treinamento.

    Args:
        df: DataFrame com colunas 'text' e 'label'

    Returns:
        DataFrame processado e LabelEncoder fitted
    """
    print("🔧 Pré-processando dados...")

    # Codificar labels
    label_encoder = LabelEncoder()
    df['label_encoded'] = label_encoder.fit_transform(df['label'])

    print(f"   ✅ {len(label_encoder.classes_)} classes identificadas\n")
    print("🏷️ Mapeamento de labels:")
    for idx, classe in enumerate(label_encoder.classes_):
        count = (df['label_encoded'] == idx).sum()
        print(f"   {idx} → {classe:20s} ({count} documentos)")
    print()

    return df, label_encoder

"""#### ============================================================================
#### 6. EXTRAÇÃO DE EMBEDDINGS
#### ============================================================================

"""

def carregar_modelo_embeddings() -> SentenceTransformer:
    """
    Carrega modelo BERT para extração de embeddings.

    Returns:
        Modelo SentenceTransformer
    """
    print(f"📥 Carregando modelo de embeddings: {MODEL_NAME}")

    model = SentenceTransformer(MODEL_NAME)

    # Verificar dispositivo
    device = 'cuda' if model.device.type == 'cuda' else 'cpu'
    print(f"   ✅ Modelo carregado no dispositivo: {device}\n")

    return model

def gerar_embeddings(
    textos: List[str],
    model: SentenceTransformer,
    batch_size: int = BATCH_SIZE,
    show_progress: bool = True
) -> np.ndarray:
    """
    Gera embeddings BERT para lista de textos.

    Args:
        textos: Lista de strings
        model: Modelo SentenceTransformer
        batch_size: Tamanho do batch para processamento
        show_progress: Mostrar barra de progresso

    Returns:
        Matriz numpy (n_samples, embedding_dim)
    """
    print(f"🔄 Gerando embeddings para {len(textos)} documentos...")

    embeddings = model.encode(
        textos,
        batch_size=batch_size,
        show_progress_bar=show_progress,
        convert_to_numpy=True,
        normalize_embeddings=False  # Normalização será feita pelo StandardScaler
    )

    print(f"   ✅ Shape dos embeddings: {embeddings.shape}\n")

    return embeddings

"""#### ============================================================================
#### 7. DEFINIÇÃO DOS MODELOS
#### ============================================================================
"""

def obter_modelos() -> Dict[str, Any]:
    """
    Define modelos clássicos de ML para teste.

    Returns:
        Dicionário com modelos configurados
    """
    modelos = {
        'Logistic Regression': LogisticRegression(
            max_iter=1000,
            random_state=SEED,
            class_weight='balanced',
            solver='lbfgs',
            n_jobs=-1
        ),

        'SVM (Linear)': SVC(
            kernel='linear',
            random_state=SEED,
            class_weight='balanced',
            probability=True
        ),

        'Random Forest': RandomForestClassifier(
            n_estimators=100,
            max_depth=10,
            random_state=SEED,
            class_weight='balanced',
            n_jobs=-1,
            min_samples_split=5,
            min_samples_leaf=2
        ),

        'XGBoost': xgb.XGBClassifier(
            n_estimators=100,
            max_depth=6,
            learning_rate=0.1,
            random_state=SEED,
            n_jobs=-1,
            eval_metric='mlogloss',
            use_label_encoder=False
        )
    }

    return modelos

"""#### ============================================================================
#### 8. VALIDAÇÃO CRUZADA
#### ============================================================================

"""

def executar_validacao_cruzada(
    df: pd.DataFrame,
    label_encoder: LabelEncoder,
    embedding_model: SentenceTransformer
) -> Dict[str, List[Dict[str, float]]]:
    """
    Executa validação cruzada estratificada para todos os modelos.

    Args:
        df: DataFrame com dados
        label_encoder: Encoder de labels
        embedding_model: Modelo para gerar embeddings

    Returns:
        Dicionário com resultados por modelo
    """
    print(f"\n{'#'*80}")
    print(f"# VALIDAÇÃO CRUZADA ESTRATIFICADA ({K_FOLDS}-FOLD)")
    print(f"{'#'*80}\n")

    # Preparar K-Fold
    skf = StratifiedKFold(n_splits=K_FOLDS, shuffle=True, random_state=SEED)

    # Obter modelos
    modelos = obter_modelos()

    # Estrutura para armazenar resultados
    resultados_por_modelo = {nome: [] for nome in modelos.keys()}
    predicoes_agregadas = {nome: {'preds': [], 'trues': []} for nome in modelos.keys()}

    # Iterar sobre folds
    for fold_num, (train_idx, test_idx) in enumerate(skf.split(df, df['label_encoded']), 1):

        print(f"\n{'='*80}")
        print(f"🔄 FOLD {fold_num}/{K_FOLDS}")
        print(f"{'='*80}\n")

        # Dividir dados
        train_fold = df.iloc[train_idx]
        test_fold = df.iloc[test_idx]

        print(f"📊 Treino: {len(train_fold)} | Teste: {len(test_fold)}")

        # Gerar embeddings
        print(f"\n🧬 Gerando embeddings do fold {fold_num}...\n")

        X_train_embeddings = gerar_embeddings(
            train_fold['text'].tolist(),
            embedding_model,
            show_progress=True
        )

        X_test_embeddings = gerar_embeddings(
            test_fold['text'].tolist(),
            embedding_model,
            show_progress=True
        )

        y_train = train_fold['label_encoded'].values
        y_test = test_fold['label_encoded'].values

        # Normalizar embeddings
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train_embeddings)
        X_test_scaled = scaler.transform(X_test_embeddings)

        print("   ✅ Embeddings normalizados\n")

        # Treinar e avaliar cada modelo
        print(f"🏋️ Treinando modelos no fold {fold_num}...\n")

        for nome_modelo, modelo in modelos.items():
            print(f"   🔹 {nome_modelo}...", end=' ')

            try:
                # Treinar
                modelo.fit(X_train_scaled, y_train)

                # Predizer
                y_pred = modelo.predict(X_test_scaled)

                # Calcular métricas
                acc = accuracy_score(y_test, y_pred)
                prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)
                rec = recall_score(y_test, y_pred, average='weighted', zero_division=0)
                f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)

                # Armazenar resultados
                resultados_por_modelo[nome_modelo].append({
                    'fold': fold_num,
                    'accuracy': acc,
                    'precision': prec,
                    'recall': rec,
                    'f1': f1
                })

                # Armazenar predições para matriz de confusão agregada
                predicoes_agregadas[nome_modelo]['preds'].extend(y_pred)
                predicoes_agregadas[nome_modelo]['trues'].extend(y_test)

                print(f"✅ F1={f1:.4f}")

            except Exception as e:
                print(f"❌ Erro: {str(e)}")
                resultados_por_modelo[nome_modelo].append({
                    'fold': fold_num,
                    'accuracy': 0,
                    'precision': 0,
                    'recall': 0,
                    'f1': 0
                })

        print()

    return resultados_por_modelo, predicoes_agregadas, label_encoder

"""#### ============================================================================
#### 9. AVALIAÇÃO E RELATÓRIOS
#### ============================================================================

"""

def gerar_relatorio_comparativo(
    resultados_por_modelo: Dict[str, List[Dict[str, float]]],
    predicoes_agregadas: Dict[str, Dict[str, List]],
    label_encoder: LabelEncoder
) -> pd.DataFrame:
    """
    Gera relatório comparativo completo entre modelos.

    Args:
        resultados_por_modelo: Resultados de cada modelo
        predicoes_agregadas: Predições agregadas
        label_encoder: Encoder de labels

    Returns:
        DataFrame com comparação
    """
    print(f"\n\n{'*'*80}")
    print(f"* RELATÓRIO FINAL - COMPARAÇÃO DE MODELOS")
    print(f"{'*'*80}\n")

    # Calcular estatísticas agregadas
    comparacao = []

    for nome_modelo, resultados in resultados_por_modelo.items():
        if len(resultados) == 0:
            continue

        accs = [r['accuracy'] for r in resultados]
        precs = [r['precision'] for r in resultados]
        recs = [r['recall'] for r in resultados]
        f1s = [r['f1'] for r in resultados]

        comparacao.append({
            'Modelo': nome_modelo,
            'Accuracy (média)': np.mean(accs),
            'Accuracy (std)': np.std(accs),
            'Precision (média)': np.mean(precs),
            'Precision (std)': np.std(precs),
            'Recall (média)': np.mean(recs),
            'Recall (std)': np.std(recs),
            'F1-Score (média)': np.mean(f1s),
            'F1-Score (std)': np.std(f1s)
        })

    df_comparacao = pd.DataFrame(comparacao)

    # Ordenar por F1-Score
    df_comparacao = df_comparacao.sort_values('F1-Score (média)', ascending=False)

    # Exibir tabela
    print("📊 TABELA COMPARATIVA:")
    print("="*80)
    print(df_comparacao.to_string(index=False))
    print("="*80)

    # Identificar melhor modelo
    melhor_modelo = df_comparacao.iloc[0]['Modelo']
    melhor_f1 = df_comparacao.iloc[0]['F1-Score (média)']

    print(f"\n🏆 MELHOR MODELO: {melhor_modelo} (F1-Score: {melhor_f1:.4f})\n")

    # Relatórios individuais
    print("\n" + "="*80)
    print("📋 RELATÓRIOS DETALHADOS POR MODELO")
    print("="*80)

    for nome_modelo in df_comparacao['Modelo']:
        preds = predicoes_agregadas[nome_modelo]['preds']
        trues = predicoes_agregadas[nome_modelo]['trues']

        print(f"\n🔹 {nome_modelo}:")
        print("-"*80)
        print(classification_report(
            trues,
            preds,
            target_names=label_encoder.classes_,
            zero_division=0,
            digits=4
        ))

    return df_comparacao, predicoes_agregadas

"""#### ============================================================================
#### 10. VISUALIZAÇÕES
#### ============================================================================

"""

def plotar_comparacao_modelos(df_comparacao: pd.DataFrame) -> None:
    """
    Plota gráfico de barras comparando modelos.

    Args:
        df_comparacao: DataFrame com métricas
    """
    print("\n📊 Gerando gráfico comparativo...")

    fig, ax = plt.subplots(figsize=(14, 8))

    x = np.arange(len(df_comparacao))
    width = 0.2

    ax.bar(x - 1.5*width, df_comparacao['Accuracy (média)'], width,
           label='Accuracy', alpha=0.8, yerr=df_comparacao['Accuracy (std)'])
    ax.bar(x - 0.5*width, df_comparacao['Precision (média)'], width,
           label='Precision', alpha=0.8, yerr=df_comparacao['Precision (std)'])
    ax.bar(x + 0.5*width, df_comparacao['Recall (média)'], width,
           label='Recall', alpha=0.8, yerr=df_comparacao['Recall (std)'])
    ax.bar(x + 1.5*width, df_comparacao['F1-Score (média)'], width,
           label='F1-Score', alpha=0.8, yerr=df_comparacao['F1-Score (std)'])

    ax.set_xlabel('Modelos', fontweight='bold', fontsize=12)
    ax.set_ylabel('Score', fontweight='bold', fontsize=12)
    ax.set_title('Comparação de Desempenho entre Modelos\n(Média ± Desvio Padrão)',
                 fontweight='bold', fontsize=14)
    ax.set_xticks(x)
    ax.set_xticklabels(df_comparacao['Modelo'], rotation=15, ha='right')
    ax.legend(loc='lower right', fontsize=10)
    ax.set_ylim(0, 1.1)
    ax.grid(axis='y', alpha=0.3)

    plt.tight_layout()
    plt.savefig('comparacao_modelos.png', dpi=150, bbox_inches='tight')
    print("   ✅ Gráfico salvo: comparacao_modelos.png")
    plt.show()

def plotar_matrizes_confusao(
    predicoes_agregadas: Dict[str, Dict[str, List]],
    label_encoder: LabelEncoder,
    df_comparacao: pd.DataFrame
) -> None:
    """
    Plota matrizes de confusão para os modelos.

    Args:
        predicoes_agregadas: Predições agregadas
        label_encoder: Encoder de labels
        df_comparacao: DataFrame com ranking
    """
    print("\n📊 Gerando matrizes de confusão...")

    # Plotar apenas os 4 modelos (ou menos se houver)
    num_modelos = min(4, len(df_comparacao))

    fig, axes = plt.subplots(2, 2, figsize=(16, 14))
    axes = axes.ravel()

    for idx, nome_modelo in enumerate(df_comparacao['Modelo'].head(num_modelos)):
        preds = predicoes_agregadas[nome_modelo]['preds']
        trues = predicoes_agregadas[nome_modelo]['trues']

        cm = confusion_matrix(trues, preds)

        sns.heatmap(
            cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=label_encoder.classes_,
            yticklabels=label_encoder.classes_,
            ax=axes[idx],
            cbar_kws={'label': 'Contagem'}
        )

        f1 = df_comparacao[df_comparacao['Modelo'] == nome_modelo]['F1-Score (média)'].values[0]

        axes[idx].set_title(f'{nome_modelo}\n(F1-Score: {f1:.4f})',
                           fontweight='bold', fontsize=11)
        axes[idx].set_ylabel('Verdadeiro', fontweight='bold')
        axes[idx].set_xlabel('Predito', fontweight='bold')

    # Remover subplots extras se houver
    for idx in range(num_modelos, 4):
        fig.delaxes(axes[idx])

    plt.suptitle('Matrizes de Confusão - Agregadas (todos os folds)',
                 fontsize=16, fontweight='bold', y=0.995)
    plt.tight_layout()
    plt.savefig('matrizes_confusao.png', dpi=150, bbox_inches='tight')
    print("   ✅ Gráfico salvo: matrizes_confusao.png")
    plt.show()

"""#### ============================================================================
#### 11. EXECUÇÃO PRINCIPAL
#### ============================================================================
"""

def main():
    """Pipeline principal de execução."""

    print("\n" + "🚀"*40)
    print("🎯 PIPELINE DE CLASSIFICAÇÃO COM BERT EMBEDDINGS")
    print("🚀"*40 + "\n")

    # 1. Carregar dataset
    csv_path = "./dataset_normalizado.csv"
    df = carregar_dataset(csv_path)

    # 2. Pré-processar
    df, label_encoder = preprocessar_dados(df)

    # 3. Carregar modelo de embeddings
    embedding_model = carregar_modelo_embeddings()

    # 4. Executar validação cruzada
    resultados, predicoes, label_enc = executar_validacao_cruzada(
        df, label_encoder, embedding_model
    )

    # 5. Gerar relatórios
    df_comparacao, predicoes_agregadas = gerar_relatorio_comparativo(
        resultados, predicoes, label_encoder
    )

    # 6. Visualizações
    plotar_comparacao_modelos(df_comparacao)
    plotar_matrizes_confusao(predicoes_agregadas, label_encoder, df_comparacao)

    print("\n" + "="*80)
    print("✅ PIPELINE CONCLUÍDO COM SUCESSO!")
    print("="*80)
    print("\n📁 Arquivos gerados:")
    print("   • comparacao_modelos.png")
    print("   • matrizes_confusao.png")
    print()

    return df_comparacao, predicoes_agregadas, label_encoder

"""#### ============================================================================
#### EXECUTAR
#### ============================================================================
"""

if __name__ == "__main__":
    df_comparacao, predicoes_agregadas, label_encoder = main()