# -*- coding: utf-8 -*-
"""Etapa 1 - Agrupar por tipo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0zOJi8DpKOCx_S6Gt17zBIb9uunUEq3
"""

import pandas as pd
import re

path = "extracted_pdf_text.csv"
df = pd.read_csv(path)

def extrair_tipo_documento(texto):
    if not isinstance(texto, str):
        return "DESCONHECIDO"

    # Captura apenas a primeira linha após "Documento id -"
    padrao = r"Documento id\s+\d+\s*-\s*([^\n\r]+)"
    match = re.search(padrao, texto, flags=re.IGNORECASE)

    if not match:
        return "DESCONHECIDO"

    tipo_bruto = match.group(1).strip().lower()

    # Normalização
    if "sentença" in tipo_bruto:
        return "Sentença"
    if "decisão" in tipo_bruto:
        return "Decisão"
    if "despacho" in tipo_bruto:
        return "Despacho"
    if "ata" in tipo_bruto:
        return "Ata de Audiência"
    if "ato ordinatório" in tipo_bruto:
        return "Ato ordinatório"
    if "acórdão" in tipo_bruto:
        return "Acórdão"

    return "Outro"

df["tipo_documento"] = df["Extracted Text"].apply(extrair_tipo_documento)
df.to_csv("extracted_pdf_text_com_tipo.csv", index=False)

contagem = (
    df["tipo_documento"]
    .value_counts()
    .reset_index()
    .rename(columns={"index": "tipo_documento", "tipo_documento": "quantidade"})
)

contagem

df_sentencas_acordaos = df[
    df["tipo_documento"].isin(["Sentença", "Acórdão"])
].copy()

df_sentencas_acordaos.to_csv(
    "extracted_pdf_text_sentencas_acordaos.csv",
    index=False
)

df_sentencas_acordaos["tipo_documento"].unique()