# -*- coding: utf-8 -*-
"""Etapa 2.1 - Pré-processamento para classificadores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HYLCa4MvTZcrTuAqoia3UPmIbS5sKKQQ
"""

# Legacy Colab cell (desativada para execução local):
# !pip install pandas tqdm chardet unidecode regex -q

import pandas as pd
import re
import regex
import chardet
import unicodedata
from tqdm import tqdm
from typing import Tuple, Dict, List
import random
import numpy as np
from collections import Counter

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

# Caminho do dataset
CAMINHO_DATASET = "./dataset_processos_filtrados_por_merito.csv"

# Nome das colunas
COLUNA_TEXTO = "Extracted Text"
COLUNA_LABEL = "decisao"

# Saída
CAMINHO_SAIDA = "./dataset_normalizado.csv"

# Segurança linguística
TAMANHO_MINIMO_TEXTO = 30

def detectar_encoding(caminho_arquivo: str) -> str:
    with open(caminho_arquivo, 'rb') as f:
        resultado = chardet.detect(f.read())
    return resultado['encoding']

def detectar_delimitador(caminho_arquivo: str, encoding: str) -> str:
    with open(caminho_arquivo, 'r', encoding=encoding) as f:
        primeira_linha = f.readline()
        if ";" in primeira_linha:
            return ";"
        return ","

def carregar_dataset(caminho: str) -> pd.DataFrame:

    encoding = detectar_encoding(caminho)
    delimitador = detectar_delimitador(caminho, encoding)

    df = pd.read_csv(caminho, encoding=encoding, sep=delimitador)

    if COLUNA_TEXTO not in df.columns:
        raise ValueError("Coluna de texto não encontrada.")

    if COLUNA_LABEL not in df.columns:
        raise ValueError("Coluna de label não encontrada.")

    return df

def normalizar_tipografia(texto: str) -> str:

    texto = texto.lower()

    texto = unicodedata.normalize("NFKC", texto)

    texto = re.sub(r'\s+', ' ', texto)
    texto = re.sub(r'\n+', ' ', texto)

    return texto.strip()

def normalizar_texto_juridico(texto: str) -> Tuple[str, Dict]:

    contadores = Counter()
    original = texto

    if not isinstance(texto, str):
        return "", contadores

    # --------------------------------------------------------
    # ✔ Remover boilerplate jurídico
    # --------------------------------------------------------

    boilerplates = [
        r'vistos[, ]*etc\.?',
        r'é o relatório',
        r'relatório dispensado',
        r'passo a decidir',
        r'ante o exposto',
        r'publique-se[, ]*registre-se[, ]*intimem-se\.?',
    ]

    for padrao in boilerplates:
        novo = re.sub(padrao, '', texto, flags=re.IGNORECASE)
        if novo != texto:
            contadores['boilerplate'] += 1
        texto = novo

    # --------------------------------------------------------
    # ✔ CNJ e números processuais
    # --------------------------------------------------------

    cnj_pattern = r'\d{7}-\d{2}\.\d{4}\.\d{1}\.\d{2}\.\d{4}'
    antigo_pattern = r'\d{2,}'

    texto, n = re.subn(cnj_pattern, ' ', texto)
    contadores['cnj'] += n

    texto, n = re.subn(r'\b\d{6,}\b', ' ', texto)
    contadores['numeros_extensos'] += n

    # --------------------------------------------------------
    # ✔ Normalizar nomes em caixa alta
    # --------------------------------------------------------

    nome_caps = r'\b[A-ZÁÉÍÓÚÂÊÔÃÕÇ]{2,}(?:\s[A-ZÁÉÍÓÚÂÊÔÃÕÇ]{2,})+\b'
    texto, n = re.subn(nome_caps, ' ', texto)
    contadores['nomes_caps'] += n

    # --------------------------------------------------------
    # ✔ Partes processuais
    # --------------------------------------------------------

    partes = r'\b(autor|réu|apelante|apelado|impetrante|impetrado)\b'
    texto, n = re.subn(partes, ' ', texto, flags=re.IGNORECASE)
    contadores['partes'] += n

    # --------------------------------------------------------
    # ✔ Datas
    # --------------------------------------------------------

    datas = [
        r'\d{2}/\d{2}/\d{4}',
        r'\d{1,2} de [a-zç]+ de \d{4}'
    ]

    for padrao in datas:
        texto, n = re.subn(padrao, ' ', texto, flags=re.IGNORECASE)
        contadores['datas'] += n

    # --------------------------------------------------------
    # ✔ Valores monetários
    # --------------------------------------------------------

    texto, n = re.subn(r'r\$ ?\d+[.,\d]*', ' ', texto, flags=re.IGNORECASE)
    contadores['valores'] += n

    # --------------------------------------------------------
    # ✔ Referências legais
    # --------------------------------------------------------

    legais = [
        r'art\.? ?\d+[ºo]?',
        r'artigo ?\d+',
        r'§ ?\d+º?',
        r'inciso [ivxlcdm]+'
    ]

    for padrao in legais:
        texto, n = re.subn(padrao, ' ', texto, flags=re.IGNORECASE)
        contadores['referencias_legais'] += n

    # --------------------------------------------------------
    # ✔ Normalização tipográfica
    # --------------------------------------------------------

    texto = normalizar_tipografia(texto)

    # --------------------------------------------------------
    # ✔ Segurança linguística
    # --------------------------------------------------------

    if len(texto) < TAMANHO_MINIMO_TEXTO:
        return original, contadores

    return texto, contadores

def aplicar_normalizacao(df: pd.DataFrame) -> Tuple[pd.DataFrame, Counter, List]:

    tqdm.pandas()

    contagem_global = Counter()
    exemplos = []

    textos_norm = []
    textos_orig = df[COLUNA_TEXTO].tolist()

    for texto in tqdm(textos_orig):

        normalizado, cont = normalizar_texto_juridico(texto)

        contagem_global.update(cont)

        if len(exemplos) < 10:
            exemplos.append((texto, normalizado))

        textos_norm.append(normalizado)

    df["texto_normalizado"] = textos_norm

    return df, contagem_global, exemplos

# ============================================================
# 📦 FUNÇÃO: RELATÓRIO ESTATÍSTICO
# ============================================================

def gerar_relatorio_transformacoes(df: pd.DataFrame,
                                   contadores: Counter,
                                   exemplos: List):

    print("\n📊 === ESTATÍSTICAS ===")

    antes = df[COLUNA_TEXTO].str.len().mean()
    depois = df["texto_normalizado"].str.len().mean()

    print(f"Tamanho médio antes: {antes:.2f}")
    print(f"Tamanho médio depois: {depois:.2f}")

    print("\n📊 Substituições realizadas:")
    for k, v in contadores.items():
        print(f"{k}: {v}")

    print("\n📊 Documentos afetados:")
    alterados = (df[COLUNA_TEXTO] != df["texto_normalizado"]).sum()
    print(alterados)

    print("\n📊 Exemplos de transformação:")
    for antes, depois in exemplos:
        print("\n--- ORIGINAL ---")
        print(antes[:400])
        print("\n--- NORMALIZADO ---")
        print(depois[:400])

def exportar_dataset(df: pd.DataFrame, caminho_saida: str):

    df_export = df[[COLUNA_TEXTO, "texto_normalizado", COLUNA_LABEL]]

    df_export.to_csv(caminho_saida, index=False)

    print(f"\n✅ Dataset exportado para: {caminho_saida}")

def main():

    print("📥 Carregando dataset...")
    df = carregar_dataset(CAMINHO_DATASET)

    print("🧹 Aplicando normalização jurídica...")
    df, contadores, exemplos = aplicar_normalizacao(df)

    print("📊 Gerando relatórios...")
    gerar_relatorio_transformacoes(df, contadores, exemplos)

    print("💾 Exportando dataset...")
    exportar_dataset(df, CAMINHO_SAIDA)

    print("\n🎯 Pipeline concluído com sucesso.")


# Execução
main()