# -*- coding: utf-8 -*-
"""Etapa 3.1 - Fine-tuning BERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJS14pq4074iSJK2cBMt7fKu6-99a_-C
"""

# Legacy Colab cells (desativadas para execução local):
# !pip uninstall -y transformers torch torchvision torchaudio sentence-transformers -q
# !pip cache purge
# !pip install torch transformers scikit-learn pandas numpy matplotlib seaborn -q

# Célula 2: Verificar (OPCIONAL)
import torch
import transformers

print(f"✅ PyTorch: {torch.__version__}")
print(f"✅ Transformers: {transformers.__version__}")
print(f"✅ CUDA: {torch.cuda.is_available()}")

import os
import numpy as np
import pandas as pd
import torch
import warnings
warnings.filterwarnings('ignore')

from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight

import matplotlib.pyplot as plt
import seaborn as sns

# Imports mínimos do transformers
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# ============================================================================
# 2. CONFIGURAÇÕES GERAIS
# ============================================================================

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"🔧 Device: {device}\n")

MODEL_NAME = "neuralmind/bert-base-portuguese-cased"
MAX_LENGTH = 512
BATCH_SIZE = 8
LEARNING_RATE = 5e-5
NUM_EPOCHS = 10
SEED = 42
K_FOLDS = 3

torch.manual_seed(SEED)
np.random.seed(SEED)

# ============================================================================
# 3. CARREGAMENTO E PRÉ-PROCESSAMENTO DO DATASET (VERSÃO CORRIGIDA)
# ============================================================================

def carregar_dataset(csv_path):
    """Carrega CSV com detecção automática"""
    print("📂 Carregando dataset...")

    delimiters = [';', ',', '\t', '|']
    encodings = ['utf-8', 'latin-1', 'iso-8859-1']

    df = None
    for delimiter in delimiters:
        for encoding in encodings:
            try:
                df = pd.read_csv(
                    csv_path,
                    encoding=encoding,
                    delimiter=delimiter,
                    on_bad_lines='skip',
                    engine='python',
                    dtype=str,
                )

                if len(df.columns) > 1 and len(df) > 0:
                    print(f"✅ Encoding: {encoding}, Delimiter: '{delimiter}'")
                    break
            except:
                continue
        if df is not None and len(df.columns) > 1:
            break

    if df is None:
        raise ValueError("❌ Não foi possível carregar CSV")

    # Normalizar colunas
    df.columns = df.columns.str.strip().str.lower()

    # Encontrar colunas
    text_col = None
    label_col = None

    for col in df.columns:
        if 'extracted' in col and 'text' in col:
            text_col = col
        if 'decisao' in col:
            label_col = col

    if text_col is None or label_col is None:
        raise ValueError(f"❌ Colunas não encontradas. Disponíveis: {df.columns.tolist()}")

    df = df[[text_col, label_col]].copy()
    df.columns = ['text', 'label']

    # Limpeza
    df['text'] = df['text'].astype(str).str.strip()
    df['label'] = df['label'].astype(str).str.strip().str.lower()

    df = df.dropna()
    df = df[df['text'].str.len() > 10]
    df = df[df['label'].str.len() > 0]

    print(f"✅ {len(df)} documentos carregados\n")
    print(df['label'].value_counts())

    return df

class TextDataset(Dataset):
    """Dataset minimalista"""

    def __init__(self, texts, labels, tokenizer, max_length=512):
        self.texts = [str(t) for t in texts]
        self.labels = [int(l) for l in labels]
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]

        encoding = self.tokenizer(
            text,
            max_length=self.max_length,
            padding='max_length',
            truncation=True,
            return_tensors='pt'
        )

        return {
            'input_ids': encoding['input_ids'].squeeze(0),
            'attention_mask': encoding['attention_mask'].squeeze(0),
            'labels': torch.tensor(label, dtype=torch.long)
        }

def treinar_modelo(train_loader, val_loader, model, optimizer, class_weights, num_epochs):
    """Treinamento simples"""

    best_val_f1 = 0
    patience = 3
    patience_counter = 0
    loss_fn = torch.nn.CrossEntropyLoss(weight=class_weights)

    for epoch in range(num_epochs):
        # Treino
        model.train()
        train_loss = 0

        for batch in train_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            optimizer.zero_grad()

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask
            )

            logits = outputs.logits
            loss = loss_fn(logits, labels)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            train_loss += loss.item()

        avg_train_loss = train_loss / len(train_loader)

        # Validação
        model.eval()
        val_preds = []
        val_trues = []

        with torch.no_grad():
            for batch in val_loader:
                input_ids = batch['input_ids'].to(device)
                attention_mask = batch['attention_mask'].to(device)
                labels = batch['labels'].to(device)

                outputs = model(input_ids=input_ids, attention_mask=attention_mask)
                logits = outputs.logits
                preds = torch.argmax(logits, dim=1)

                val_preds.extend(preds.cpu().numpy())
                val_trues.extend(labels.cpu().numpy())

        val_f1 = f1_score(val_trues, val_preds, average='weighted', zero_division=0)
        val_acc = accuracy_score(val_trues, val_preds)

        print(f"Epoch {epoch+1}/{num_epochs}: Loss={avg_train_loss:.4f}, Val_Acc={val_acc:.4f}, Val_F1={val_f1:.4f}")

        if val_f1 > best_val_f1:
            best_val_f1 = val_f1
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print("⏹️ Early stopping\n")
                break

    return model

def avaliar_modelo(test_loader, model):
    """Avaliação simples"""

    model.eval()
    test_preds = []
    test_trues = []

    with torch.no_grad():
        for batch in test_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            preds = torch.argmax(logits, dim=1)

            test_preds.extend(preds.cpu().numpy())
            test_trues.extend(labels.cpu().numpy())

    accuracy = accuracy_score(test_trues, test_preds)
    precision = precision_score(test_trues, test_preds, average='weighted', zero_division=0)
    recall = recall_score(test_trues, test_preds, average='weighted', zero_division=0)
    f1 = f1_score(test_trues, test_preds, average='weighted', zero_division=0)

    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'predictions': test_preds,
        'true_labels': test_trues,
        'confusion_matrix': confusion_matrix(test_trues, test_preds)
    }

def executar_cv(df, label_encoder):
    """K-Fold"""

    print(f"\n{'#'*70}")
    print(f"# VALIDAÇÃO CRUZADA ({K_FOLDS}-FOLD)")
    print(f"{'#'*70}\n")

    skf = StratifiedKFold(n_splits=K_FOLDS, shuffle=True, random_state=SEED)

    results = []
    all_preds = []
    all_trues = []

    fold_num = 1
    for train_idx, test_idx in skf.split(df, df['label_encoded']):
        print(f"\n{'='*70}")
        print(f"🔄 FOLD {fold_num}/{K_FOLDS}")
        print(f"{'='*70}\n")

        train_fold = df.iloc[train_idx].copy()
        test_fold = df.iloc[test_idx].copy()

        # Split treino
        train_data, val_data = train_test_split(
            train_fold,
            test_size=0.2,
            stratify=train_fold['label_encoded'],
            random_state=SEED
        )

        # =============================
        # Calcular pesos das classes
        # =============================
        class_weights = compute_class_weight(
            class_weight="balanced",
            classes=np.unique(train_data['label_encoded']),
            y=train_data['label_encoded']
        )

        class_weights = torch.tensor(class_weights, dtype=torch.float).to(device)

        print(f"📊 Treino: {len(train_data)}, Val: {len(val_data)}, Teste: {len(test_fold)}\n")

        # Datasets
        train_dataset = TextDataset(
            train_data['text'].tolist(),
            train_data['label_encoded'].tolist(),
            tokenizer,
            MAX_LENGTH
        )

        val_dataset = TextDataset(
            val_data['text'].tolist(),
            val_data['label_encoded'].tolist(),
            tokenizer,
            MAX_LENGTH
        )

        test_dataset = TextDataset(
            test_fold['text'].tolist(),
            test_fold['label_encoded'].tolist(),
            tokenizer,
            MAX_LENGTH
        )

        # DataLoaders
        train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
        val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE)
        test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE)

        # Modelo
        print("📥 Carregando modelo...\n")
        model = AutoModelForSequenceClassification.from_pretrained(
            MODEL_NAME,
            num_labels=len(label_encoder.classes_),
            ignore_mismatched_sizes=True
        ).to(device)

        optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)

        # Treinar
        print("🏋️ Treinando...\n")
        model = treinar_modelo(train_loader, val_loader, model, optimizer, class_weights, NUM_EPOCHS)

        # Avaliar
        print("📊 Avaliando...\n")
        fold_result = avaliar_modelo(test_loader, model)

        print(f"Accuracy:  {fold_result['accuracy']:.4f}")
        print(f"Precision: {fold_result['precision']:.4f}")
        print(f"Recall:    {fold_result['recall']:.4f}")
        print(f"F1-Score:  {fold_result['f1']:.4f}\n")

        results.append(fold_result)
        all_preds.extend(fold_result['predictions'])
        all_trues.extend(fold_result['true_labels'])

        fold_num += 1

    return results, all_preds, all_trues

def relatorio_final(results, all_preds, all_trues, label_encoder):
    """Relatório"""

    print(f"\n\n{'*'*70}")
    print(f"* RELATÓRIO FINAL")
    print(f"{'*'*70}\n")

    accs = [r['accuracy'] for r in results]
    f1s = [r['f1'] for r in results]

    print("📊 Resultados por Fold:")
    for i, (acc, f1) in enumerate(zip(accs, f1s), 1):
        print(f"   Fold {i}: Acc={acc:.4f}, F1={f1:.4f}")

    print(f"\n✅ Média Accuracy: {np.mean(accs):.4f} ± {np.std(accs):.4f}")
    print(f"✅ Média F1-Score: {np.mean(f1s):.4f} ± {np.std(f1s):.4f}")

    print("\n" + "="*70)
    print("📋 Relatório de Classificação:")
    print("="*70)
    print(classification_report(
        all_trues, all_preds,
        target_names=label_encoder.classes_,
        zero_division=0
    ))

    # Plot
    cm = confusion_matrix(all_trues, all_preds)
    fig, ax = plt.subplots(figsize=(10, 8))
    sns.heatmap(
        cm, annot=True, fmt='d', cmap='Blues',
        xticklabels=label_encoder.classes_,
        yticklabels=label_encoder.classes_,
        ax=ax, cbar_kws={'label': 'Contagem'}
    )
    plt.title('Matriz de Confusão Agregada', fontsize=14, fontweight='bold')
    plt.ylabel('Verdadeiro')
    plt.xlabel('Predito')
    plt.tight_layout()
    plt.savefig('matriz_confusao.png', dpi=150, bbox_inches='tight')
    print("\n✅ Gráfico salvo: matriz_confusao.png")
    plt.show()

try:
    from transformers import AutoModelForSequenceClassification, AutoTokenizer
    print("✅ Importação bem-sucedida!")

    # Teste com um modelo simples
    model_name = "distilbert-base-uncased"
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(model_name)
    print("✅ Modelo carregado com sucesso!")

except Exception as e:
    print(f"❌ Erro: {e}")

# Carregar dados
df = carregar_dataset("./dataset_processes_to_classifier_exported1.csv")

# Codificar labels
label_encoder = LabelEncoder()
df['label_encoded'] = label_encoder.fit_transform(df['label'])

print(f"\n🏷️ Mapeamento:")
for idx, classe in enumerate(label_encoder.classes_):
    print(f"   {idx} → {classe}")

# Carregar tokenizer
print(f"\n📥 Carregando tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# Validação cruzada
results, all_preds, all_trues = executar_cv(df, label_encoder)

# Relatório
relatorio_final(results, all_preds, all_trues, label_encoder)

print("\n" + "="*70)
print("✅ TREINAMENTO CONCLUÍDO!")
print("="*70)